server:
  port: 8080

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/webshoe"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

#api:
#  prefix: api/v1

outbound:
  identity:
    client-id: "id"
    client-secret: "secretKey"
    redirect-uri: "http://localhost:3000/authenticate"

payment:
  vnPay:
    url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
    returnUrl: "http://localhost:8080/payment/vn-pay-callback"
    tmnCode: "id"
    secretKey: "secretKey"
    version: "2.1.0"
    command: "pay"
    orderType: "order-type"

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 36000 # in second
  refreshable-duration: 36000 # in seconds